### ISSUE TITLE
"Admin contact" broken since version 1.7.8

### ISSUE THREAD

**Issue by bttrx** [auge8472/My-Little-Forum-1#50]
Hi,

I receive only a blank page when clicking "Admin contact". The log says "PHP Fatal error: Uncaught Error: Call to undefined function htmlsc() in [snip]/www/forum/contact.php:33".

Proposed solution: Move the line `include("inc.php");` to the top of the file. At least before the line `if (isset($_GET['forum_contact'])) $forum_contact = htmlsc($_GET['forum_contact']);`.

Thanks and cheers,
Robert

**Comment by auge8472** [comment]
> Proposed solution: Move the line include("inc.php"); to the top of the file.

That's the correct solution. I'll fix it within the next minutes for contact.php and further script files.

**Comment by auge8472** [comment]
Fix for version 1.7.10 in c41558061a57  
Fix for version 1.8 will follow
