### ISSUE TITLE
"Mark thread" not working in mlf 1.7.9

### ISSUE THREAD

**Issue by bttrx** [auge8472/My-Little-Forum-1#52]
Hi Heiko!

I don't see the icon changing to a red-crossed bullet, after clicking the bullet for "Mark thread". It works fine in mlf 1.7.6.
Any idea?

Robert

**Comment by auge8472** [comment]
Hmm, I can confirm the misbehaviour in my testing forum. I'll take a look into the issue.

**Comment by bttrx** [comment]
Gotcha(, I think)! Remove ' from "' WHERE tid= " in line 231 of admin.php.

**Comment by auge8472** [comment]
Good spot! Thank you.

**Comment by auge8472** [comment]
Closed it with 6b307f4868b3597745861a23e3145a496b64524f for 1.8
and with d6d6a6cd91264f93bffd41dcb111f3551a621c7f for 1.7.x.
